#!/usr/bin/env python3
"""Generate src/dsp/kr106_ui_hierarchy.h from src/module.json.

The Schwung shadow UI gets the parameter hierarchy from the DSP itself
(get_param("ui_hierarchy") / get_param("chain_params")) — NOT from
module.json — so the hierarchy must be compiled into dsp.so (same pattern
as schwung-hera). module.json stays the single source of truth; run this
after editing it (build.sh runs it automatically).

Transforms applied for the DSP copy:
- root level becomes a preset-browser level (list_param/count_param/
  name_param) so the jog wheel browses presets there, like hera;
  the "preset" int param is dropped from root params/knobs and the knob
  slot is backfilled with "decay".
- chain_params: flat de-duplicated array of every param (enums exposed as
  int 0..N-1 — Schwung sends enum values as 0-based indices).
"""
import json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SRC = os.path.join(ROOT, 'src', 'module.json')
DST = os.path.join(ROOT, 'src', 'dsp', 'kr106_ui_hierarchy.h')

module = json.load(open(SRC))
hier = json.loads(json.dumps(module['capabilities']['ui_hierarchy']))  # deep copy

levels = hier['levels']
root = levels['root']
root['list_param'] = 'preset'
root['count_param'] = 'preset_count'
root['name_param'] = 'preset_name'
root['children'] = None
root['params'] = [p for p in root['params'] if p.get('key') != 'preset']
root['knobs'] = ['decay' if k == 'preset' else k for k in root['knobs']]
hier.setdefault('modes', None)

# flat chain_params from every unique param object
seen = {}
for lv in levels.values():
    for p in lv.get('params', []):
        if not isinstance(p, dict) or 'key' not in p or p['key'] in seen:
            continue
        cp = {'key': p['key'], 'name': p.get('label', p['key'])}
        if p.get('type') == 'enum':
            cp['type'] = 'int'
            cp['min'] = 0
            cp['max'] = len(p.get('options', [])) - 1
        else:
            cp['type'] = p.get('type', 'float')
            cp['min'] = p.get('min', 0)
            cp['max'] = p.get('max', 1)
        seen[p['key']] = cp
chain_params = list(seen.values())

def c_str(name, obj):
    j = json.dumps(obj, separators=(',', ':'))
    # chunk BEFORE escaping so escape sequences never split across lines
    chunks = [j[i:i+96] for i in range(0, len(j), 96)]
    def esc(c): return c.replace('\\', '\\\\').replace('"', '\\"')
    body = '\n    '.join('"%s"' % esc(c) for c in chunks)
    return 'static const char %s[] =\n    %s;\n' % (name, body)

out = ('/* AUTO-GENERATED by scripts/gen_ui_hierarchy.py from src/module.json.\n'
       ' * Do not edit by hand — edit module.json and regenerate. */\n'
       '#pragma once\n\n'
       + c_str('kUiHierarchyJson', hier)
       + '\n'
       + c_str('kChainParamsJson', chain_params))
open(DST, 'w').write(out)
print('wrote %s (%d + %d bytes JSON)' % (DST,
      len(json.dumps(hier, separators=(",", ":"))),
      len(json.dumps(chain_params, separators=(",", ":")))))
